// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: grpc/pb/location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long    float32 `protobuf:"fixed32,1,opt,name=long,proto3" json:"long,omitempty"`
	Lat     float32 `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Speed   float32 `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading float32 `protobuf:"fixed32,4,opt,name=heading,proto3" json:"heading,omitempty"`
}

func (x *SendLocationRequest) Reset() {
	*x = SendLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLocationRequest) ProtoMessage() {}

func (x *SendLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLocationRequest.ProtoReflect.Descriptor instead.
func (*SendLocationRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_location_proto_rawDescGZIP(), []int{0}
}

func (x *SendLocationRequest) GetLong() float32 {
	if x != nil {
		return x.Long
	}
	return 0
}

func (x *SendLocationRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SendLocationRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SendLocationRequest) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type SendLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendLocationResponse) Reset() {
	*x = SendLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pb_location_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLocationResponse) ProtoMessage() {}

func (x *SendLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_location_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLocationResponse.ProtoReflect.Descriptor instead.
func (*SendLocationResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_location_proto_rawDescGZIP(), []int{1}
}

func (x *SendLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_pb_location_proto protoreflect.FileDescriptor

var file_grpc_pb_location_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6b, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x30, 0x0a, 0x14,
	0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x57,
	0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4b, 0x0a, 0x0c, 0x53, 0x65,
	0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pb_location_proto_rawDescOnce sync.Once
	file_grpc_pb_location_proto_rawDescData = file_grpc_pb_location_proto_rawDesc
)

func file_grpc_pb_location_proto_rawDescGZIP() []byte {
	file_grpc_pb_location_proto_rawDescOnce.Do(func() {
		file_grpc_pb_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pb_location_proto_rawDescData)
	})
	return file_grpc_pb_location_proto_rawDescData
}

var file_grpc_pb_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_pb_location_proto_goTypes = []interface{}{
	(*SendLocationRequest)(nil),  // 0: proto.SendLocationRequest
	(*SendLocationResponse)(nil), // 1: proto.SendLocationResponse
}
var file_grpc_pb_location_proto_depIdxs = []int32{
	0, // 0: proto.Location.SendLocation:input_type -> proto.SendLocationRequest
	1, // 1: proto.Location.SendLocation:output_type -> proto.SendLocationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_pb_location_proto_init() }
func file_grpc_pb_location_proto_init() {
	if File_grpc_pb_location_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_pb_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pb_location_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pb_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_location_proto_goTypes,
		DependencyIndexes: file_grpc_pb_location_proto_depIdxs,
		MessageInfos:      file_grpc_pb_location_proto_msgTypes,
	}.Build()
	File_grpc_pb_location_proto = out.File
	file_grpc_pb_location_proto_rawDesc = nil
	file_grpc_pb_location_proto_goTypes = nil
	file_grpc_pb_location_proto_depIdxs = nil
}
